# .github/workflows/build.yml

name: Build and Test C/CPP Files

on:
  push:
    paths:
      - 'C/**'
      - 'CPP/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Build C files
      run: |
        for file in $(find C -type f -name "*.c"); do
          if [ -f "$file" ]; then
            echo "Building $file"
            gcc -o "${file%.c}.out" "$file" 2> build_errors.log
            if [ $? -ne 0 ]; then
              echo "Build failed for $file"
              cat build_errors.log
              exit 1
            fi
          else
            echo "Skipping $file as it is not a valid file"
          fi
        done

    - name: Build CPP files
      run: |
        for file in $(find CPP -type f -name "*.cpp"); do
          if [ -f "$file" ]; then
            echo "Building $file"
            g++ -o "${file%.cpp}.out" "$file" 2> build_errors.log
            if [ $? -ne 0 ]; then
              echo "Build failed for $file"
              cat build_errors.log
              exit 1
            fi
          else
            echo "Skipping $file as it is not a valid file"
          fi
        done
